[iso_codes]
git-tree-sha1 = "cfd934a7f0be6c6f30849e1bf66151f64f6c0ea3"

    [[iso_codes.download]]
    sha256 = "9ebd9223ba8d531ead5e587e627971b5091e0bcbca88cfe33cb3f9a24e0c4c65"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.10.0+0/iso_codes.v4.10.0.any.tar.gz"
