[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
os = "macos"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.aarch64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.aarch64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.aarch64-linux-musl.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.aarch64-unknown-freebsd.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.armv6l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.armv6l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.armv7l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.armv7l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.i686-linux-gnu.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.i686-linux-musl.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "b41a8e3e5c9a0e7fed818211670a99cfb46be9ab"
os = "windows"

    [[iso_codes.download]]
    sha256 = "f099941cd5bf1d407a57134bda50721a6a736f951e5052ef1bf36672ea722305"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.i686-w64-mingw32.tar.gz"
[[iso_codes]]
arch = "powerpc64le"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.powerpc64le-linux-gnu.tar.gz"
[[iso_codes]]
arch = "riscv64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.riscv64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
os = "macos"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.x86_64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.x86_64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.x86_64-linux-musl.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "5f861513373ad9bd18851024df22f8024ef80854"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "ce82a12d9e1a096c55dd35261907291a1bef6c807a6823cb75caccff41b401b8"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.x86_64-unknown-freebsd.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "b41a8e3e5c9a0e7fed818211670a99cfb46be9ab"
os = "windows"

    [[iso_codes.download]]
    sha256 = "f099941cd5bf1d407a57134bda50721a6a736f951e5052ef1bf36672ea722305"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.20.1+0/iso_codes.v4.20.1.x86_64-w64-mingw32.tar.gz"
