[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
os = "macos"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.aarch64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.aarch64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.aarch64-linux-musl.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.aarch64-unknown-freebsd.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.armv6l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.armv6l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.armv7l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.armv7l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.i686-linux-gnu.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.i686-linux-musl.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "b076c3113b98ad9ef330b11e8b0bbfe5eb6f365c"
os = "windows"

    [[iso_codes.download]]
    sha256 = "13aa863bfcb2df5e40451ea5cf6d1ad6a895ce117eb4809afb22afbf9e28d673"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.i686-w64-mingw32.tar.gz"
[[iso_codes]]
arch = "powerpc64le"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.powerpc64le-linux-gnu.tar.gz"
[[iso_codes]]
arch = "riscv64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.riscv64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
os = "macos"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.x86_64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.x86_64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.x86_64-linux-musl.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "97c8b42554915632bb6b0f94b1d8dc1109f7fad1"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "9011ace3c6e732448d45f2a640a76cbfcabac88517a8f9deb383b7e752b5bb63"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.x86_64-unknown-freebsd.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "b076c3113b98ad9ef330b11e8b0bbfe5eb6f365c"
os = "windows"

    [[iso_codes.download]]
    sha256 = "13aa863bfcb2df5e40451ea5cf6d1ad6a895ce117eb4809afb22afbf9e28d673"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.17.0+0/iso_codes.v4.17.0.x86_64-w64-mingw32.tar.gz"
