[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
os = "macos"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.aarch64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.aarch64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "aarch64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.aarch64-linux-musl.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.armv6l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.armv6l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.armv7l-linux-gnueabihf.tar.gz"
[[iso_codes]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.armv7l-linux-musleabihf.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.i686-linux-gnu.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.i686-linux-musl.tar.gz"
[[iso_codes]]
arch = "i686"
git-tree-sha1 = "1719102ef324df43b9fe123a231c2ee630931a03"
os = "windows"

    [[iso_codes.download]]
    sha256 = "dd8b379d713ffa9751e50bfacdfe1fa13db11409bda063676ff2978501ddb45c"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.i686-w64-mingw32.tar.gz"
[[iso_codes]]
arch = "powerpc64le"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.powerpc64le-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
os = "macos"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.x86_64-apple-darwin.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "glibc"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.x86_64-linux-gnu.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
libc = "musl"
os = "linux"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.x86_64-linux-musl.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "695a3abd0af051dab62687501b9a61ad91c831a3"
os = "freebsd"

    [[iso_codes.download]]
    sha256 = "50fc043881557667ea5c970358485aa7cef604d808542547d51a305944ca2bcc"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.x86_64-unknown-freebsd.tar.gz"
[[iso_codes]]
arch = "x86_64"
git-tree-sha1 = "1719102ef324df43b9fe123a231c2ee630931a03"
os = "windows"

    [[iso_codes.download]]
    sha256 = "dd8b379d713ffa9751e50bfacdfe1fa13db11409bda063676ff2978501ddb45c"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.15.1+0/iso_codes.v4.15.1.x86_64-w64-mingw32.tar.gz"
