[iso_codes]
git-tree-sha1 = "71f68a3d55d73f2e15a3969c241fae2349b1feb5"

    [[iso_codes.download]]
    sha256 = "a27ef364abdfad2d051ddbb5458b1ef7b9290cc429e54c2509f2d4afc3651a19"
    url = "https://github.com/JuliaBinaryWrappers/iso_codes_jll.jl/releases/download/iso_codes-v4.11.0+0/iso_codes.v4.11.0.any.tar.gz"
